trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ShrewdSpirit Docker'
    repository: 'shrewdspirit/simpleserv'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: 'latest'
    addPipelineData: false
